import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "@/common/components/layout/header";
import Footer from "@/common/components/layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section>
          <nav>
            <Header />
          </nav>
          {children}
          <nav>
            <Footer />
          </nav>
        </section>
      </body>
    </html>
  );
}
